insert into staff (Id, active, email, first_name, last_name, last_updated, password, payment_id, picture_url, username, address_address_id, store_id) values (1, false, 'ssissot0@seattletimes.com', 'Sella', 'Sissot', '2021-05-13 07:42:17', '8N0g109rR', 1, 'http://dummyimage.com/106x100.png/5fa2dd/ffffff', 'ssissot0', 1, 1);
insert into staff (Id, active, email, first_name, last_name, last_updated, password, payment_id, picture_url, username, address_address_id, store_id) values (2, true, 'smarusik1@fc2.com', 'Sadella', 'Marusik', '2021-11-18 10:17:29', 'dm7mdSurI', 2, 'http://dummyimage.com/111x100.png/5fa2dd/ffffff', 'smarusik1', 2, 2);
insert into staff (Id, active, email, first_name, last_name, last_updated, password, payment_id, picture_url, username, address_address_id, store_id) values (3, true, 'bbucklan2@canalblog.com', 'Betteann', 'Bucklan', '2021-06-13 17:38:44', 'EpjYj31r', 3, 'http://dummyimage.com/143x100.png/dddddd/000000', 'bbucklan2', 3, 3);
insert into staff (Id, active, email, first_name, last_name, last_updated, password, payment_id, picture_url, username, address_address_id, store_id) values (4, true, 'eannett3@sun.com', 'Elset', 'Annett', '2021-03-30 11:57:24', 'VQ3Ob9EZyeKo', 4, 'http://dummyimage.com/130x100.png/ff4444/ffffff', 'eannett3', 4, 4);
insert into staff (Id, active, email, first_name, last_name, last_updated, password, payment_id, picture_url, username, address_address_id, store_id) values (5, false, 'phavers4@indiegogo.com', 'Pet', 'Havers', '2022-01-11 17:50:15', 'LE4Yip', 5, 'http://dummyimage.com/151x100.png/ff4444/ffffff', 'phavers4', 5, 5);
insert into staff (Id, active, email, first_name, last_name, last_updated, password, payment_id, picture_url, username, address_address_id, store_id) values (6, true, 'cmowle5@macromedia.com', 'Caroljean', 'Mowle', '2021-07-29 14:49:35', 'I1U9zbZZ9l', 6, 'http://dummyimage.com/147x100.png/dddddd/000000', 'cmowle5', 6, 6);
insert into staff (Id, active, email, first_name, last_name, last_updated, password, payment_id, picture_url, username, address_address_id, store_id) values (7, true, 'ecoatsworth6@alibaba.com', 'Eleonora', 'Coatsworth', '2021-06-28 14:59:52', 'h6KGZvppcznY', 7, 'http://dummyimage.com/181x100.png/5fa2dd/ffffff', 'ecoatsworth6', 7, 7);
insert into staff (Id, active, email, first_name, last_name, last_updated, password, payment_id, picture_url, username, address_address_id, store_id) values (8, false, 'cesch7@elpais.com', 'Chadwick', 'Esch', '2022-01-06 09:30:07', 'UUTaHoI', 8, 'http://dummyimage.com/147x100.png/dddddd/000000', 'cesch7', 8, 8);
insert into staff (Id, active, email, first_name, last_name, last_updated, password, payment_id, picture_url, username, address_address_id, store_id) values (9, false, 'jgooderridge8@shutterfly.com', 'Janean', 'Gooderridge', '2021-12-09 09:23:44', '4oKNla7A', 9, 'http://dummyimage.com/159x100.png/cc0000/ffffff', 'jgooderridge8', 9, 9);
insert into staff (Id, active, email, first_name, last_name, last_updated, password, payment_id, picture_url, username, address_address_id, store_id) values (10, true, 'bpoles9@discuz.net', 'Bella', 'Poles', '2022-03-01 04:12:43', 'TSBIlV', 10, 'http://dummyimage.com/105x100.png/5fa2dd/ffffff', 'bpoles9', 10, 10);
# Rows:

